#!/bin/bash
# make this file executable and pass it the 4 arguments below as strings.
# example if this file were an executable called print_cover
# execute:
# print_cover "Full Stack Engineer" "Company Name" "My reasons" "My skills"
# enclose in "" if any spaces in the arguments
# write a template called cover in the same directory
# place __postion __company __reason __skills in the template where you want to perform sed string substitution
# the file will be output to the command line as well as copied to clipboard. A cover_log file will also be generated
position=$1
company=$2
reason=$3
skills=$4

if [[ -n "$position" ]]; then
    echo "${position}"
else
    echo "argument error"
fi

if [[ -n "$company" ]]; then
    echo "${company}"
else
    echo "argument error"
fi

if [[ -n "$reason" ]]; then
    echo "${reason}"
else
    echo "argument error"
fi

if [[ -n "$skills" ]]; then
    echo "${skills}"
else
    echo "argument error"
fi

echo
echo
echo "appended date position company reason skills to cover_log"
echo "-------------------------------------------------------------------------" >> cover_log
date >> cover_log
echo ${position} >> cover_log
echo ${company} >> cover_log
echo ${reason} >> cover_log
echo ${skills} >> cover_log  

echo "******************************************************************"
echo "******************************************************************"

cat ./cover | sed "s/__position/${position}/g" | sed "s/__company/${company}/g" | sed "s/__reason/${reason}/g" | sed "s/__skills/${skills}/g" | tee >(pbcopy)
